config/routes.rb
Rails.application.routes.draw do
  get "/reservations/top/:day", to: "reservations#top", as: "reservations_top"
  post "/reservations/create", to: "reservations#create", as: "reservations_create"
  patch "/reservations/update/:id", to: "reservations#update", as: "reservations_update"
  post "/reservations/destroy/:id", to: "reservations#destroy", as: "reservations_destroy"
  post "/reservations/change_date/:way/:difference", to: "reservations#change_date", as: "reservations_change_date"
  post "/reservations/edit/:id", to: "reservations#edit", as: "reservations_edit"
  
  get "/login", to: "sessions#login_form", as: "login_form"
  post "/login", to: "sessions#login", as: "login"
  post "/logout", to: "sessions#logout", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/holiday.rb
class Holiday < ApplicationRecord
    validates :date, {presence: true}
    validates :user_id, {presence: true}
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :name, {presence: true}
    validates :date, {presence: true}
    validates :visit_time, {presence: true}
    validates :required_time, {presence: true}
    validates :menu, {presence: true}
    validates :user_id, {presence: true}

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



  def set_reservation_info
    @visit_times = [["◯◯:◯◯", nil], "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00"]
    @required_times = [["◯分", nil], "30分", "1時間", "1時間30分", "2時間", "2時間30分", "3時間"]
    @new = true
  end

  def set_dates(date)
    @dates = []
    i = 0
    while i < 4 do
      @dates.push(date + i)
      i += 1
    end
  end 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def top
    @reservation = Reservation.new(date: params[:day].to_date)
    set_reservation_info
    set_dates(params[:day].to_date)
    @reservations_one = Reservation.where(date: @dates[0])
  end

  def create
    @reservation = Reservation.new(name: params[:reservation][:name],
                                   menu: params[:reservation][:menu],
                                   date: params[:reservation][:date],
                                   visit_time: params[:reservation][:visit_time],
                                   required_time: params[:reservation][:required_time],
                                   memo: params[:reservation][:memo],
                                   user_id: 1)
    if @reservation.save
      flash[:notice] = "予約を追加しました"
      redirect_to(reservations_top_path(@reservation.date))
    else
      set_dates(@reservation.date)
      set_reservation_info 
      render("reservations/top")                          
    end
  end

  def edit
    @reservation = Reservation.find_by(id: params[:id])
    set_dates(@reservation.date)
    set_reservation_info 
    @new = false
    render("reservations/top")
  end

  def update
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.name = params[:reservation][:name]
    @reservation.menu = params[:reservation][:menu]
    @reservation.date = params[:reservation][:date]
    @reservation.visit_time = params[:reservation][:visit_time]
    @reservation.required_time = params[:reservation][:required_time]
    @reservation.memo = params[:reservation][:memo]
    if @reservation.save
      flash[:notice] = "予約を変更しました"
      redirect_to(reservations_top_path(@reservation.date))
    else
      set_dates(@reservation.date)
      set_reservation_info 
      @new = false
      render("reservations/top")                          
    end    
  end
 
  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to(reservations_top_path(@reservation.date))
  end

  def change_date
    set_dates(Date.today + params[:difference].to_i + params[:way].to_i)
    @reservation = Reservation.new(date: @dates[0])
    set_reservation_info
    render("reservations/top")
  end




  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login_form
        
    end

    def login
        user = User.find_by(id: 1) 

        if user.authenticate(params[:session][:password]) 
            session[:admin] = true
            redirect_to(reservations_top_path(Date.today))
        else
            render("sessions/login_form")
        end

    end

    def logout
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HairVoir</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if flash[:notice] %>
      <div id="flash"><span class="fas fa-bell"></span> <%= flash[:notice] %></div>
      <script>
        $(function(){
          $("#flash").fadeOut(2000);
        });
      </script>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reservations/_edit.html.erb
    <div id="reservation-edit">
        <h1>予約変更</h1>
        <%= render "error_messages" %>
            <div class="reservation-form">
            <%= form_for(@reservation, url: reservations_update_path(@reservation.id)) do |f| %>
                <p><%= f.text_field :name, :placeholder => "氏名", :class => "name-field" %>様</p> 
                <p>メニュー：<%= f.select :menu, ["カット", "カラー", "パーマ", "その他"] %></p>
                <p>
                    日付：<%= f.date_field :date, :class => "date-field" %><br>
                    来店時間：<%= f.select :visit_time, @visit_times %><br>
                    所要時間：<%= f.select :required_time, @required_times %>
                </p>
                <p><%= f.text_field :memo, :placeholder => "メモ", :class => "memo-field" %></p>
                <%= f.submit "予約を変更する", :class => "reservation-btn edit-btn" %>
                <%= link_to("削除", reservations_destroy_path(@reservation.id), method: :post, :class => "reservation-btn destroy-btn")%>
            <% end %>
        </div>
    </div>

app/views/reservations/_error_messages.html.erb
<div class="error_message">
    <div>
        <span class="far fa-times-circle close-error"></span>
        <div class="clear"></div>
    </div>
    <% @reservation.errors.full_messages.each do |error_message| %>
        <p><span class="fas fa-exclamation-triangle"></span> <%= error_message %></p>
    <% end %>
</div>  

<% if @reservation.errors.full_messages[0] %>
    <script>
        $(function(){
            $(".error_message").addClass("active");
        })
        $(".close-error").click(function(){
             $(".error_message").removeClass("active");
        });
    </script>
<% end%>  

app/views/reservations/_index.html.erb
<div id="reservation-index">
    <h1>予約一覧</h1>
    <div class="time-list">
        <h2>
            <div class="change-date">
                <% difference = @dates[0] - Date.today %>
                <%= link_to("＜", reservations_change_date_path(-1, difference), method: :post) %>                
            </div>
            <div class="change-date">
                <%= link_to("＞", reservations_change_date_path(1, difference), method: :post) %>                
            </div>                
        </h2>
        <% @visit_times.shift(1) %>
        <% @visit_times.each do |visit_time| %>
            <p><%= visit_time %></p>
        <% end %>
    </div>
    <script>
        $(function(){
            for(var i = 0; i < 24 ; i += 1){
                if (i % 2 == 0){
                    $(".time-list").children("p").eq(i).css("font-weight", "bold");
                 }
            }
         });
    </script>    
    <% time_table_count = 0 %>
    <% while time_table_count < 4 do%>
        <div class="time-table">
            <div class="date">
                <%= "#{@dates[time_table_count].month}月#{@dates[time_table_count].day}日(#{%w(日 月 火 水 木 金 土)[@dates[time_table_count].wday]})" %>
                <div class="time-warning">
                    <span class="far fa-times-circle close-time-warning"></span>
                    <p>予約時間が重複しています</p>
                </div>
                <span class="fas fa-exclamation-triangle time-warning-icon"></span>
            </div>

            <% table_count = 0 %>
            <% while table_count < 2 do %>
                <div class="table">
                    <% p_count = 0 %>
                    <% while p_count < 24 do %>
                        <p></p>

                        <% p_count += 1 %>   
                    <% end %>
                    <h2></h2> 
                </div>
                <% table_count += 1 %>
            <% end %>
        </div>
        <% time_table_count += 1 %>
    <% end %>
</div>

<p id="data-pass"></p>
<% @time_table_number = 0 %>
<% while @time_table_number < 4 %>
    <script>
        $(function(){
            $("#data-pass").attr("data-table-number", "<%= @time_table_number %>");
        });
    </script>
    <% @p_number = 0 %>
    <% while @p_number < 24 %>      
        <% @p_number += 1 %>
        <script>
            $(function(){
                $("#data-pass").attr("data-p-number", "<%= @p_number %>");
            });
        </script>
        <% @reservations_this_time = Reservation.where(date: @dates[@time_table_number], visit_time: @visit_times[@p_number], user_id: 1) %>

        <% if @reservations_this_time.length >= 1 %>
            <script>
                $(function(){
                    var $data_pass = $("#data-pass");
                    var $p_n = $data_pass.attr("data-p-number");
                    $data_pass.attr("data-p-length", "<%= @required_times.index(@reservations_this_time[0].required_time) %>");
                    var $p_l = Number($data_pass.attr("data-p-length")) - 1;
                    var $table_block = $(".time-table").eq($data_pass.attr("data-table-number")).children(".table");
                    if (!$table_block.eq(0).children("p").eq($p_n).hasClass("visit-time")){
                        $table_block.eq(0).children("p").eq($p_n).html('<%= link_to("#{@reservations_this_time[0][:name]} 様", reservations_edit_path(@reservations_this_time[0][:id]), method: :post) %>').addClass("visit-time visit-time1");
                        for (var i = 1; i <= $p_l; i += 1){
                            var p_length =  Number($p_n) + i;
                            $table_block.eq(0).children("p").eq(p_length).addClass("visit-time required-time1");
                            if (i == $p_l){
                                $table_block.eq(0).children("p").eq(p_length).addClass("end-time");
                            }
                        }
                    } else if (!$table_block.eq(1).children("p").eq($p_n).hasClass("visit-time")){
                        $table_block.eq(1).children("p").eq($p_n).html('<%= link_to("#{@reservations_this_time[0][:name]} 様", reservations_edit_path(@reservations_this_time[0][:id]), method: :post) %>').addClass("visit-time visit-time2");
                        for(var i = 1; i <= $p_l; i += 1){
                            var p_length =  Number($p_n) + i;
                            $table_block.eq(1).children("p").eq(p_length).addClass("visit-time required-time2");
                            if (i == $p_l){
                                $table_block.eq(1).children("p").eq(p_length).addClass("end-time");
                            }
                        }
                    } else {
                        $(".date").eq($data_pass.attr("data-table-number")).children("div").append('<h4><%= link_to("・#{@reservations_this_time[0][:name]} 様 #{@reservations_this_time[0][:visit_time]}〜", reservations_edit_path(@reservations_this_time[0][:id]), method: :post) %></h4>');
                    }
                });
            </script>
            <% if @reservations_this_time.length >= 2 %>
            <script>
                $(function(){
                    var $data_pass = $("#data-pass");
                    var $p_n = $data_pass.attr("data-p-number");
                    $data_pass.attr("data-p-length", "<%= @required_times.index(@reservations_this_time[1].required_time) %>");
                    var $p_l = Number($data_pass.attr("data-p-length")) - 1;
                    var $table_block = $(".time-table").eq($data_pass.attr("data-table-number")).children(".table");
                    if (!$table_block.eq(1).children("p").eq($p_n).hasClass("visit-time")){
                        $table_block.eq(1).children("p").eq($p_n).html('<%= link_to("#{@reservations_this_time[1][:name]} 様", reservations_edit_path(@reservations_this_time[1][:id]), method: :post) %>').addClass("visit-time visit-time2");
                        for (var i = 1; i <= $p_l; i += 1){
                            var p_length =  Number($p_n) + i;
                            $table_block.eq(1).children("p").eq(p_length).addClass("visit-time required-time2");
                            if (i == $p_l){
                                $table_block.eq(1).children("p").eq(p_length).addClass("end-time");
                            }
                        }
                    } else {
                        $(".date").eq($data_pass.attr("data-table-number")).children("div").append('<h4><%= link_to("・#{@reservations_this_time[1][:name]} 様 #{@reservations_this_time[1][:visit_time]}〜", reservations_edit_path(@reservations_this_time[1][:id]), method: :post) %></h4>');
                    }
                });
            </script>                
            <% end %>
        <% end %>
    <% end %>
    <% @time_table_number += 1 %>
<% end %>

<script>
    $(function(){
        for(var i = 0; i < 192 ; i += 1){
            if (i % 2 == 0){
                 $(".table").children("p").eq(i).css("border-top-style", "solid");
             }
             if ($(".time-warning").eq(i).children("h4").length > 0){
                 $(".date").eq(i).children(".time-warning-icon").show();
             }                    
        }
        $(".time-warning-icon").click(function(){
            var $time_warning = $(this).parent().children(".time-warning");
            if ($time_warning.children("h4").length > 0){
                $(this).css("color", "orange").css("font-size", "18px");
                $time_warning.addClass("active");
            }
        });
        $(".close-time-warning").click(function(){
            $(this).parent().parent().children(".time-warning-icon").css("color", "red").css("font-size", "16px");
            $(this).parent().removeClass("active");
        });
    });
</script>    

app/views/reservations/_new.html.erb
<div id="reservation-new">
    <h1>予約追加</h1>
    <%= render "error_messages" %>
        <div class="reservation-form">
        <%= form_for(@reservation, url: reservations_create_path) do |f| %>
            <p><%= f.text_field :name, :placeholder => "氏名", :class => "name-field" %>様</p> 
            <p>メニュー：<%= f.select :menu, ["カット", "カラー", "パーマ", "その他"] %></p>
            <p>
                日付：<%= f.date_field :date, :class => "date-field" %><br>
                来店時間：<%= f.select :visit_time, @visit_times %><br>
                所要時間：<%= f.select :required_time, @required_times %>
            </p>
            <p><%= f.text_field :memo, :placeholder => "メモ", :class => "memo-field" %></p>
            <%= f.submit "予約を追加する", :class => "reservation-btn" %>
        <% end %>
    </div>
</div> 

app/views/reservations/top.html.erb
<div id="reservation-top">
    <div class="menu">
        <%= link_to("更新", reservations_top_path(Date.today), data: {"turbolinks"=>false}) %>
    </div>
    <% if @new %>
        <%= render "new" %>
    <% else %>
        <%= render "edit" %>
    <% end %>   
    <%= render "index" %>
    <div class="clear"></div>
</div>